FROM golang:1.22.4-alpine

RUN apk add --no-cache gcc musl-dev
RUN apk add --no-cache sqlite

WORKDIR /app

COPY . .
RUN CGO_ENABLED=1 go build -ldflags="-w -s" -o server ./cmd/app/main.go 
ENV PORT=8090

CMD ["./server"]
